window.stateData = [
    { State: 'ALL', Desc: 'All States' },
    { State: 'FL', Desc: 'Florida' },
    { State: 'AK', Desc: 'Alaska' },
    { State: 'AL', Desc: 'Alabama' },
    { State: 'AR', Desc: 'Arkansas' },
    { State: 'AZ', Desc: 'Arizona' },
    { State: 'CA', Desc: 'California' },
    { State: 'CT', Desc: 'Connecticut' },
    { State: 'CO', Desc: 'Colorado' },
    { State: 'DC', Desc: 'District of Columbia' },
    { State: 'DE', Desc: 'Delaware' },
    { State: 'GA', Desc: 'Georgia' },
    { State: 'HI', Desc: 'Hawaii' },
    { State: 'IA', Desc: 'Iowa' },
    { State: 'ID', Desc: 'Idaho' },
    { State: 'IL', Desc: 'Illinois' },
    { State: 'IN', Desc: 'Indiana' },
    { State: 'KS', Desc: 'Kansas' },
    { State: 'KY', Desc: 'Kentucky' },
    { State: 'LA', Desc: 'Louisiana' },
    { State: 'MA', Desc: 'Massachusetts' },
    { State: 'MD', Desc: 'Maryland' },
    { State: 'ME', Desc: 'Maine' },
    { State: 'MI', Desc: 'Michigan' },
    { State: 'MN', Desc: 'Minnesota' },
    { State: 'MO', Desc: 'Missouri' },
    { State: 'MS', Desc: 'Mississippi' },
    { State: 'MT', Desc: 'Montana' },
    { State: 'NC', Desc: 'North Carolina ' },
    { State: 'ND', Desc: 'North Dakota' },
    { State: 'NE', Desc: 'Nebraska' },
    { State: 'NH', Desc: 'New Hampshire' },
    { State: 'NJ', Desc: 'New Jersey' },
    { State: 'NM', Desc: 'New Mexico' },
    { State: 'NV', Desc: 'Nevada' },
    { State: 'NY', Desc: 'New York' },
    { State: 'OH', Desc: 'Ohio' },
    { State: 'OK', Desc: 'Oklahoma' },
    { State: 'OR', Desc: 'Oregon' },
    { State: 'PA', Desc: 'Pennsylvania' },
    { State: 'RI', Desc: 'Rhode Island' },
    { State: 'SC', Desc: 'South Carolina' },
    { State: 'SD', Desc: 'South Dakota' },
    { State: 'TN', Desc: 'Tennessee' },
    { State: 'TX', Desc: 'Texas' },
    { State: 'UT', Desc: 'Utah' },
    { State: 'VA', Desc: 'Virginia' },
    { State: 'VT', Desc: 'Vermont' },
    { State: 'WA', Desc: 'Washington' },
    { State: 'WI', Desc: 'Wisconsin' },
    { State: 'WV', Desc: 'West Virginia' },
    { State: 'WY', Desc: 'Wyoming' },
    { State: 'INT', Desc: 'International' },
    { State: 'OTH', Desc: 'Other' },
    { State: 'AA', Desc: 'Armed Forces Americas' },
    { State: 'AE', Desc: 'Armed Forces Europe' },
    { State: 'AP', Desc: 'Armed Forces Pacific' },
    { State: 'AS', Desc: 'American Soma' },
    { State: 'FM', Desc: 'Federated States Of Micronesia' },
    { State: 'GU', Desc: 'Guam' },
    { State: 'MH', Desc: 'Marshall Islands' },
    { State: 'MP', Desc: 'Northern Mariana Islands' },
    { State: 'PR', Desc: 'Puerto Rico' },
    { State: 'PW', Desc: 'Palau' },
    { State: 'VI', Desc: 'Virgin Islands' },
];

window.stateData = window.stateData.map(function(item) {
    item.searchtxt = item.State + item.Desc;
    item.searchtxt = item.searchtxt.toUpperCase();
    return item;
});